# Generated by Django 5.2.3 on 2025-06-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(default=50.2),
            preserve_default=False,
        ),
    ]
