# Generated by Django 5.2.3 on 2025-06-17 20:40

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_restaurant_latitude_alter_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'get_latest_by': 'date_opened', 'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
